version: "3"
services:
  web:
    #image: node:alpine Local dockerfile
    build: .
    container_name: go-paint
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:3000"
    networks:
      - webnet
    volumes:
      - ./:/app
    command: yarn start
networks:
  webnet: